import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  app: {
    backgroundColor: '#F7F4EC',
    flex: 1,
  },
  stackContent: {
    backgroundColor: '#F7F4EC',
  },
  scrollContent: {
    gap: 22,
    paddingBottom: 108,
    paddingHorizontal: 20,
    paddingTop: 68,
  },
  detailContent: {
    gap: 16,
    paddingBottom: 36,
    paddingHorizontal: 20,
    paddingTop: 22,
  },
  header: {
    gap: 12,
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  brandLockup: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
  },
  blindspotMark: {
    alignItems: 'center',
    backgroundColor: '#25231D',
    borderCurve: 'continuous',
    borderRadius: 999,
    height: 32,
    justifyContent: 'center',
    width: 32,
  },
  blindspotCore: {
    backgroundColor: '#F7F4EC',
    borderCurve: 'continuous',
    borderRadius: 999,
    height: 12,
    opacity: 0.72,
    width: 12,
  },
  brand: {
    color: '#25231D',
    fontSize: 30,
    fontWeight: '800',
    letterSpacing: 0,
  },
  headerText: {
    color: '#5F5C52',
    fontSize: 17,
    lineHeight: 25,
  },
  settingsButton: {
    backgroundColor: '#F0EDE5',
    borderColor: '#DDD4C3',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 11,
    paddingVertical: 8,
  },
  settingsButtonText: {
    color: '#5F5C52',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  screenStack: {
    gap: 16,
  },
  sectionLabelRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  kicker: {
    color: '#246B65',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  contextLabel: {
    color: '#777368',
    flexShrink: 1,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'right',
  },
  metricsRow: {
    flexDirection: 'row',
    gap: 10,
  },
  metricCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED0',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    flex: 1,
    gap: 4,
    padding: 13,
  },
  metricValue: {
    color: '#25231D',
    fontSize: 22,
    fontWeight: '900',
  },
  metricLabel: {
    color: '#777368',
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  biasCard: {
    backgroundColor: '#FFFDF7',
    borderColor: '#E1D9C7',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    gap: 18,
    padding: 20,
  },
  biasMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  biasMeta: {
    backgroundColor: '#F0EDE5',
    borderCurve: 'continuous',
    borderRadius: 8,
    color: '#5F5C52',
    fontSize: 12,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  biasTitle: {
    color: '#25231D',
    fontSize: 31,
    fontWeight: '800',
    letterSpacing: 0,
    lineHeight: 36,
  },
  biasStory: {
    color: '#34312A',
    fontSize: 19,
    lineHeight: 29,
  },
  definitionBox: {
    backgroundColor: '#E9F0EA',
    borderColor: '#C8D8D2',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    gap: 8,
    padding: 14,
  },
  definitionLabel: {
    color: '#246B65',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  definitionText: {
    color: '#25231D',
    fontSize: 16,
    lineHeight: 24,
  },
  reflectionCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED0',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    padding: 18,
  },
  cardLabel: {
    color: '#7C4A28',
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    textTransform: 'uppercase',
  },
  reflectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  inlineButton: {
    backgroundColor: '#F0EDE5',
    borderCurve: 'continuous',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  inlineButtonText: {
    color: '#5F5C52',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  reflectionQuestion: {
    color: '#25231D',
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 28,
  },
  journalInput: {
    backgroundColor: '#F7F4EC',
    borderColor: '#D8CFBC',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    color: '#25231D',
    fontSize: 16,
    lineHeight: 23,
    minHeight: 118,
    padding: 14,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: '#25231D',
    borderCurve: 'continuous',
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 15,
  },
  primaryButtonText: {
    color: '#FFFDF7',
    fontSize: 16,
    fontWeight: '800',
  },
  disabledButton: {
    backgroundColor: '#AAA59A',
  },
  tellCard: {
    backgroundColor: '#EDF4F6',
    borderColor: '#C5D7DD',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 18,
  },
  tellText: {
    color: '#25231D',
    fontSize: 17,
    lineHeight: 25,
  },
  practiceCard: {
    backgroundColor: '#FFFDF7',
    borderColor: '#E1D9C7',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    gap: 18,
    padding: 20,
  },
  scenarioText: {
    color: '#25231D',
    fontSize: 22,
    fontWeight: '700',
    lineHeight: 31,
  },
  answerStack: {
    gap: 10,
  },
  answerButton: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D8CFBC',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    padding: 16,
  },
  answerButtonCorrect: {
    backgroundColor: '#E1F1E3',
    borderColor: '#81B48A',
  },
  answerButtonWrong: {
    backgroundColor: '#F7E8E3',
    borderColor: '#C98972',
  },
  answerText: {
    color: '#25231D',
    fontSize: 17,
    fontWeight: '700',
  },
  feedbackCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED0',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    gap: 13,
    padding: 18,
  },
  feedbackText: {
    color: '#34312A',
    fontSize: 17,
    lineHeight: 25,
  },
  secondaryButton: {
    alignItems: 'center',
    backgroundColor: '#EDF4F6',
    borderColor: '#C5D7DD',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  secondaryButtonText: {
    color: '#195D66',
    fontSize: 16,
    fontWeight: '800',
  },
  emptyCard: {
    backgroundColor: '#FFFDF7',
    borderColor: '#E1D9C7',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 18,
  },
  emptyTitle: {
    color: '#25231D',
    fontSize: 21,
    fontWeight: '800',
  },
  emptyText: {
    color: '#5F5C52',
    fontSize: 16,
    lineHeight: 24,
  },
  entryCard: {
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED0',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    gap: 10,
    padding: 16,
  },
  entryHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
  },
  entryBias: {
    color: '#25231D',
    flex: 1,
    fontSize: 17,
    fontWeight: '800',
  },
  entryDate: {
    color: '#777368',
    fontSize: 13,
    fontWeight: '700',
  },
  entryText: {
    color: '#34312A',
    fontSize: 16,
    lineHeight: 24,
  },
  entryActions: {
    flexDirection: 'row',
    gap: 8,
  },
  entryActionButton: {
    backgroundColor: '#EDF4F6',
    borderColor: '#C5D7DD',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  entryDeleteButton: {
    backgroundColor: '#F7E8E3',
    borderColor: '#C98972',
  },
  entryActionText: {
    color: '#195D66',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  entryDeleteText: {
    color: '#8F3E2C',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  collectionContent: {
    gap: 14,
    paddingBottom: 108,
    paddingHorizontal: 20,
    paddingTop: 68,
  },
  collectionHeaderStack: {
    gap: 18,
  },
  collectionSearchCard: {
    backgroundColor: '#FFFDF7',
    borderColor: '#E1D9C7',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  searchInput: {
    backgroundColor: '#FFFFFF',
    borderColor: '#D8CFBC',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    color: '#25231D',
    fontSize: 16,
    minHeight: 46,
    paddingHorizontal: 13,
  },
  filterList: {
    marginHorizontal: -2,
  },
  filterChip: {
    backgroundColor: '#F0EDE5',
    borderColor: '#DDD4C3',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    marginHorizontal: 2,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  filterChipActive: {
    backgroundColor: '#25231D',
    borderColor: '#25231D',
  },
  filterChipText: {
    color: '#5F5C52',
    fontSize: 13,
    fontWeight: '800',
  },
  filterChipTextActive: {
    color: '#FFFDF7',
    fontSize: 13,
    fontWeight: '900',
  },
  collectionGroup: {
    gap: 10,
  },
  collectionSectionHeader: {
    alignItems: 'center',
    backgroundColor: '#F7F4EC',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 2,
    paddingTop: 8,
  },
  collectionTitle: {
    color: '#25231D',
    fontSize: 18,
    fontWeight: '800',
  },
  collectionCount: {
    color: '#777368',
    fontSize: 13,
    fontWeight: '800',
  },
  collectionItem: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#E4DED0',
    borderCurve: 'continuous',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    padding: 15,
  },
  collectionItemLocked: {
    backgroundColor: '#F0EDE5',
  },
  collectionCopy: {
    flex: 1,
    gap: 4,
  },
  collectionNameRow: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  collectionName: {
    color: '#25231D',
    flex: 1,
    fontSize: 16,
    fontWeight: '800',
  },
  collectionSeen: {
    backgroundColor: '#E1F1E3',
    borderCurve: 'continuous',
    borderRadius: 8,
    color: '#246B65',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    textTransform: 'uppercase',
  },
  collectionUnseen: {
    backgroundColor: '#F0EDE5',
    borderCurve: 'continuous',
    borderRadius: 8,
    color: '#777368',
    fontSize: 11,
    fontWeight: '900',
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    textTransform: 'uppercase',
  },
  collectionDefinition: {
    color: '#34312A',
    fontSize: 15,
    lineHeight: 22,
  },
  collectionNameLocked: {
    color: '#8D8B82',
    fontSize: 16,
    fontWeight: '800',
  },
  collectionMeta: {
    color: '#777368',
    fontSize: 13,
    fontWeight: '600',
  },
  collectionAction: {
    color: '#246B65',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  collectionActionLocked: {
    color: '#8D8B82',
    fontSize: 13,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  tabBar: {
    backgroundColor: '#FFFDF7',
    borderColor: '#DDD4C3',
    borderTopWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    gap: 8,
    left: 0,
    paddingBottom: 28,
    paddingHorizontal: 12,
    paddingTop: 12,
    position: 'absolute',
    right: 0,
  },
  tabButton: {
    alignItems: 'center',
    borderCurve: 'continuous',
    borderRadius: 8,
    flex: 1,
    minHeight: 46,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  tabButtonActive: {
    backgroundColor: '#25231D',
  },
  tabButtonInactive: {
    backgroundColor: '#F0EDE5',
  },
  tabTextActive: {
    color: '#FFFDF7',
    fontSize: 12,
    fontWeight: '900',
  },
  tabTextInactive: {
    color: '#5F5C52',
    fontSize: 12,
    fontWeight: '800',
  },
  pressed: {
    opacity: 0.72,
  },
});
